<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SL3S66O" failures="1" tests="2" name="Test" time="8.405" errors="0" timestamp="23 Feb 2023 18:37:29 GMT">
  <testcase classname="com.lambdatest.TestNGTodo1" name="basicTest" time="4.336"/>
  <testcase classname="com.lambdatest.TestNGTodo1" name="basicTest2" time="0.001">
    <failure type="java.lang.AssertionError" message="Intentional failure">
      <![CDATA[java.lang.AssertionError: Intentional failure
at com.lambdatest.TestNGTodo1.basicTest2(TestNGTodo1.java:92)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- basicTest2 -->
</testsuite> <!-- Test -->
