<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SL3S66O" failures="1" tests="2" name="com.lambdatest.TestNGTodo1" time="8.354" errors="0" timestamp="23 Feb 2023 18:37:29 GMT" skipped="0">
  <testcase classname="com.lambdatest.TestNGTodo1" name="basicTest2" time="2.388">
    <failure message="Intentional failure" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Intentional failure
at org.testng.Assert.fail(Assert.java:96)
at com.lambdatest.TestNGTodo1.basicTest2(TestNGTodo1.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- basicTest2 -->
  <testcase classname="com.lambdatest.TestNGTodo1" name="basicTest" time="5.966"/>
</testsuite> <!-- com.lambdatest.TestNGTodo1 -->
